# Generated by Django 5.0.6 on 2024-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='')),
                ('datetime', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
